version: "3.8"

services:
  api:
    build: .
    container_name: bathroom-designer-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
